export const MAIN = 'MAIN';

export const MAIN_GIFTS = 'MAIN_GIFTS';
export const MAIN_PROFILE = 'MAIN_PROFILE';
export const MAIN_BOOKS = 'MAIN_BOOKS';
export const MAIN_COURSES = 'MAIN_COURSES';

export const MAIN_BOOKS_SAVAT = 'MAIN_BOOKS_SAVAT';
export const MAIN_BOOKS_SAVAT_ORDER = 'MAIN_BOOKS_SAVAT_ORDER';
export const MAIN_BOOKS_SAVAT_ORDER_COURER = 'MAIN_BOOKS_SAVAT_ORDER_COURER';
export const MAIN_BOOKS_SAVAT_ORDER_PICKUP = 'MAIN_BOOKS_SAVAT_ORDER_PICKUP';
